development: &default
  adapter: postgresql
  encoding: unicode
  database: chisafepath_development
  pool: 5
  username: chisafepath
  password:
  min_messages: WARNING
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: chisafepath_production
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: <%= ENV['IP'] %>
  min_messages: WARNING
