development: &default
  adapter: postgis
  encoding: unicode
  database: chisafepath_development
  pool: 5
  username: chisafepath
  password:
  min_messages: WARNING
  host: localhost
  port: 5432

production:
  adapter: postgis
  encoding: unicode
  database: <%= Rails.application.secrets.prod_db_name %>
  host: <%= Rails.application.secrets.prod_db_host %>
  pool: 5
  username: <%= Rails.application.secrets.prod_db_username %>
  password: <%= Rails.application.secrets.prod_db_password %>
  min_messages: WARNING
