development: &default
  adapter: postgis
  encoding: unicode
  database: chisafepath_development
  pool: 5
  username: postgres
  password:
  min_messages: WARNING
  host: postgis
  port: 5432 

production:
  adapter: postgis
  encoding: unicode
  database: chisafepath_production
  host: localhost
  pool: 5
  username: chisafepath
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
  min_messages: WARNING
